### ISSUE TITLE
GotoSocial建站实例无法与留言板互动

### ISSUE THREAD

**Issue by KyoSakuyo** [wxwmoe/wxwClub#5]
使用GotoSocial建立站点后，每次尝试与ovo.st互动，都显示pending状态，无法连接上，无法关注or互动。

**Comment by KyoSakuyo** [comment]
我在[Gotosocial发了一个Issue](https://github.com/superseriousbusiness/gotosocial/issues/1863), GoToSocial的开发者排查日志后并没有发现什么异常，判断结果为似乎没有什么是他们那边可以做的……

他们希望侦错的工作可以由wxwClub的开发者来暂行。

**Comment by cdn0x12** [comment]
我的GotoSocial实例也复现了这个问题。

顺便link一下Gotosocial那边的issue： superseriousbusiness/gotosocial/issues/1863

**Comment by KyoSakuyo** [comment]
By the way, 如果开发者需要GoToSocial的实例来测试侦错的话，我想我可以有空闲的vps提供给你，
倒也很抱歉没有更多code的能力来提供更多帮助，感谢~

**Comment by cdn0x12** [comment]
刚刚测试了一下：

互动时wxwClub会验证失败（`log/inbox`目录出现`verify_failed`文件），例如当发送关注请求时，wxwClub的日志如下：

### Input
```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "actor": "https://<GOTOSOCIAL_URL>/users/<GOTOSOCIAL_USERNAME>",
    "id": "https://<GOTOSOCIAL_URL>/users/<GOTOSOCIAL_USERNAME>/follow/014KQSFFEJDZVBDKEFZ26RGW3X",
    "object": "https://<WXWCLUB_URL>/club/board",
    "to": "https://<WXWCLUB_URL>/club/board",
    "type": "Follow"
}
```

### Server
```json
{
    "USER": "www-data",
    "HOME": "/var/www",
    "HTTP_ACCEPT_ENCODING": "gzip",
    "HTTP_CONTENT_LENGTH": "275",
    "HTTP_CONTENT_TYPE": "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"",
    "HTTP_SIGNATURE": "keyId=\"https://<GOTOSOCIAL_URL>/users/<GOTOSOCIAL_USERNAME>/main-key\",algorithm=\"hs2019\",headers=\"(request-target) host date digest\",signature=\"MJipKvwD2sKUxkTvvhgQX/m7oNuz98gwh5je0NtimVMAqiu85X5TZQMPCgWB5mA1y2t1mqdd3AxSQEwKQvbmNvZimkUOYmox2BLuuGE3N3VH1SdDBmwiVJJAfn3kYJQedLYuN+tDbSzKBe+V0fn70cORccSymHjvi3EhViy/Yo68Pba4UEvwfZiaY/Z65xLaaBz5FhhZ9LCKEL5nhvI2k9ejR0LteM5Jo6h8RdgNmht5xmkOpdeyUFKOmZyGqlcV0NswIz1/c3MhibV0j5Qxl2UYtmkD+FiyCYUAnlhq0Ex8mIRqsewpM2+lR/jHR39lC2QDlMTAEddj5X8Q1YZ5/g==\"",
    "HTTP_DIGEST": "SHA-256=G/Lg++DfdXM5wdNzQg+LNVa6pMrrqApHozAAsyZGVs4=",
    "HTTP_DATE": "Tue, 09 Jan 2024 03:38:14 GMT",
    "HTTP_USER_AGENT": "gotosocial (+https://<GOTOSOCIAL_URL>) gotosocial/0.13.0 git-f4fcffc",
    "HTTP_ACCEPT_CHARSET": "utf-8",
    "HTTP_HOST": "<WXWCLUB_URL>",
    "REDIRECT_STATUS": "200",
    "SERVER_NAME": "<WXWCLUB_URL>",
    "SERVER_PORT": "443",
    "SERVER_ADDR": "155.138.209.7",
    "REMOTE_USER": "",
    "REMOTE_PORT": "40956",
    "REMOTE_ADDR": "172.18.0.2",
    "SERVER_SOFTWARE": "nginx/1.25.3",
    "GATEWAY_INTERFACE": "CGI/1.1",
    "HTTPS": "on",
    "REQUEST_SCHEME": "https",
    "SERVER_PROTOCOL": "HTTP/2.0",
    "DOCUMENT_ROOT": "/var/www/wxwClub",
    "DOCUMENT_URI": "/index.php",
    "REQUEST_URI": "/inbox",
    "SCRIPT_NAME": "/index.php",
    "CONTENT_LENGTH": "275",
    "CONTENT_TYPE": "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"",
    "REQUEST_METHOD": "POST",
    "QUERY_STRING": "",
    "SCRIPT_FILENAME": "/var/www/wxwClub/index.php",
    "PATH_INFO": "",
    "FCGI_ROLE": "RESPONDER",
    "PHP_SELF": "/index.php",
    "REQUEST_TIME_FLOAT": 1704771494.601217,
    "REQUEST_TIME": 1704771494
}
```

数据库里的`user`表没有出现对应用户的记录

**Comment by cdn0x12** [comment]
我基本确定了问题原因：

1. Gotosocial 的 actor 和 main key之间是用 `/` 而不是用 `#` 隔开的，且GotoSocial的follow request发送到的是wxwClub的shared inbox 而非 特定club的inbox。
2. Gotosocial 发送的 signature 中 algorithm 字段使用的是 `hs2019` 并默认用 `rsa-sha256` 签名，wxwClub 目前只接受明确指定的算法，遇到这种情形没有 fallback。
3. 收到 mention 时，GotoSocial 的 to 字段有可能不是数组，而 wxwClub 的 Announce Process 只支持数组情形。

稍后提出PR。

---

I've identified the cause of the problem:

1. In Gotosocial, the actor and main key are separated by `/` instead of `#`, and the follow request from GotoSocial is sent to the shared inbox of wxwClub, not to the inbox of a specific club.
2. The algorithm field in the signature sent by Gotosocial uses `hs2019` and defaults to signing with `rsa-sha256`. Currently, wxwClub only accepts explicitly specified algorithms and does not have a fallback for this situation.
3. When receiving a mention, the 'to' field in GotoSocial might not be an array, while wxwClub's Announce Process only supports array scenarios.

Proposing a PR.

**Comment by cdn0x12** [comment]
PR参见 #6 ，请求 @fghrsh review

---

PR was proposed on #6. `@fghrsh` could you kindly review this at your earliest convenience?

**Comment by fghrsh** [comment]
@CDN18 (> ʌ <) 感谢 PR，目前已合并到 ovo.st 的运行代码里了，简单测试了下无异常。
